<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Job_Portal_Website</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\JobApplications\**" />
    <Compile Remove="Views\JobListings\**" />
    <Content Remove="Views\JobApplications\**" />
    <Content Remove="Views\JobListings\**" />
    <EmbeddedResource Remove="Views\JobApplications\**" />
    <EmbeddedResource Remove="Views\JobListings\**" />
    <None Remove="Views\JobApplications\**" />
    <None Remove="Views\JobListings\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\Downloads\RegisterEmployer.cshtml" Link="Views\Account\RegisterEmployer.cshtml" />
    <None Include="..\..\..\Downloads\RegisterJobSeeker.cshtml" Link="Views\Account\RegisterJobSeeker.cshtml" />
    <None Include="JobPortalWebsite.slnx" />
  </ItemGroup>

</Project>
