// <auto-generated />
using System;
using Job_Portal_Website.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Job_Portal_Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260722172215_MakeOptionalFieldsNullable")]
    partial class MakeOptionalFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Job_Portal_Website.Models.Application", b =>
                {
                    b.Property<int>("applyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("applyId"));

                    b.Property<int>("JobListingjobListId")
                        .HasColumnType("int");

                    b.Property<DateTime>("appliedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("applyStatus")
                        .HasColumnType("int");

                    b.Property<int>("jobListId")
                        .HasColumnType("int");

                    b.Property<int>("jobSeekerId")
                        .HasColumnType("int");

                    b.HasKey("applyId");

                    b.HasIndex("JobListingjobListId");

                    b.HasIndex("jobSeekerId", "jobListId")
                        .IsUnique();

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.Employer", b =>
                {
                    b.Property<int>("employerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employerId"));

                    b.Property<string>("companyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employerDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("employerIndustry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employerId");

                    b.HasIndex("employerEmail")
                        .IsUnique();

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.JobListing", b =>
                {
                    b.Property<int>("jobListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobListId"));

                    b.Property<int>("employerId")
                        .HasColumnType("int");

                    b.Property<bool>("isClosed")
                        .HasColumnType("bit");

                    b.Property<string>("jobDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobRequirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("jobSalary")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("postedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("jobListId");

                    b.HasIndex("employerId");

                    b.ToTable("JobListing");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.JobSeeker", b =>
                {
                    b.Property<int>("jobSeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobSeekerId"));

                    b.Property<string>("resumePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seekerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("seekerExp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seekerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seekerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seekerSkills")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobSeekerId");

                    b.HasIndex("seekerEmail")
                        .IsUnique();

                    b.ToTable("JobSeeker");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.Application", b =>
                {
                    b.HasOne("Job_Portal_Website.Models.JobListing", "JobListing")
                        .WithMany("Applications")
                        .HasForeignKey("JobListingjobListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Job_Portal_Website.Models.JobSeeker", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("jobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobListing");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.JobListing", b =>
                {
                    b.HasOne("Job_Portal_Website.Models.Employer", "Employer")
                        .WithMany("JobListings")
                        .HasForeignKey("employerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.Employer", b =>
                {
                    b.Navigation("JobListings");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.JobListing", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Job_Portal_Website.Models.JobSeeker", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
